// Centralized Skills Taxonomy config
// Exported for use across services and screens

import { Stamp } from "../types/dashboard";

export type SkillsTaxonomy = Record<string, string[]>;

export const SKILLS_TAXONOMY: SkillsTaxonomy = {
  "Human Skills": [
    "Communication",
    "Collaboration",
    "Leadership",
    "Empathy",
    "Active Listening",
    "Conflict Resolution",
    "Networking",
    "Public Speaking",
    "Team Management",
  ],
  "Meta-Learning": [
    "Critical Thinking",
    "Research Skills",
    "Self-Reflection",
    "Learning Strategies",
    "Information Synthesis",
    "Knowledge Transfer",
    "Continuous Learning",
    "Adaptability",
  ],
  "Maker & Builder": [
    "Prototyping",
    "Design Thinking",
    "Craftsmanship",
    "Innovation",
    "Technical Skills",
    "Project Management",
    "Problem Solving",
    "Creative Construction",
    "Engineering",
  ],
  "Civic Impact": [
    "Community Engagement",
    "Social Responsibility",
    "Advocacy",
    "Volunteer Work",
    "Policy Understanding",
    "Cultural Awareness",
    "Environmental Stewardship",
    "Civic Participation",
  ],
  "Creative Expression": [
    "Artistic Creation",
    "Storytelling",
    "Music",
    "Writing",
    "Visual Arts",
    "Performance",
    "Creative Problem Solving",
    "Imagination",
    "Aesthetic Appreciation",
  ],
  "Problem-Solving": [
    "Analytical Thinking",
    "Strategic Planning",
    "Troubleshooting",
    "Decision Making",
    "Systems Thinking",
    "Root Cause Analysis",
    "Innovation",
    "Logic",
    "Pattern Recognition",
  ],
  "Work Experience": [
    "Professional Skills",
    "Industry Knowledge",
    "Workplace Etiquette",
    "Time Management",
    "Client Relations",
    "Business Acumen",
    "Career Development",
    "Mentorship",
  ],
  "Future Self": [
    "Goal Setting",
    "Vision Creation",
    "Personal Growth",
    "Skill Development",
    "Career Planning",
    "Life Balance",
    "Self-Improvement",
    "Aspiration Mapping",
  ],
};

//Common Skills variations for better matching
export const SKILL_SYNONYMS: Record<string, string[]> = {
  Communication: [
    "communicating",
    "speaking",
    "talking",
    "expressing",
    "communication skills",
    "verbal communication",
  ],
  Collaboration: ["collaborating", "teamwork", "working together", "cooperative work", "team work"],
  Leadership: ["leading", "managing people", "guiding", "mentoring", "leading teams"],
  "Critical Thinking": [
    "analyzing",
    "critical analysis",
    "thinking critically",
    "analytical skills",
    "reasoning",
  ],
  "Problem Solving": [
    "solving problems",
    "troubleshooting",
    "finding solutions",
    "problem resolution",
  ],
  Creativity: ["being creative", "creative thinking", "innovation", "creative work"],
  "Design Thinking": ["designing", "design", "user experience", "ux design", "design process"],
  "Project Management": [
    "managing projects",
    "project planning",
    "organizing work",
    "project coordination",
  ],
  "Technical Skills": ["coding", "programming", "technical work", "technology", "tech skills"],
  "Public Speaking": ["presenting", "presentations", "speaking publicly", "giving talks"],
  Writing: ["written communication", "content creation", "authoring", "composing"],
  "Research Skills": ["researching", "investigation", "studying", "gathering information"],
  "Time Management": ["managing time", "scheduling", "planning", "organizing time"],
  "Goal Setting": ["setting goals", "planning goals", "objective setting", "target setting"],
};

export const AVAILABLE_STAMPS: Stamp[] = [
  //Academic Stamps
  {
    id: "math",
    name: "Mathematics",
    icon: "🧮",
    category: "Academic",
    description: "Completed mathematics course",
    unlocked: false,
  },
  {
    id: "science",
    name: "Science Scholar",
    icon: "🔬",
    category: "Academic",
    description: "Excelled in science subjects",
    unlocked: false,
  },
  {
    id: "literature",
    name: "Literature Lover",
    icon: "📚",
    category: "Academic",
    description: "Studied literature and languages",
    unlocked: false,
  },
  {
    id: "history",
    name: "History Buff",
    icon: "🏛️",
    category: "Academic",
    description: "Passionate about history",
    unlocked: false,
  },
  {
    id: "arts",
    name: "Creative Artist",
    icon: "🎨",
    category: "Academic",
    description: "Pursued arts and creativity",
    unlocked: false,
  },
  {
    id: "music",
    name: "Music Maestro",
    icon: "🎵",
    category: "Academic",
    description: "Talented in music c",
    unlocked: false,
  },
  //Achievement Stamps

  {
    id: "deans_list",
    name: "Dean's List",
    icon: "⭐",
    category: "Achievement",
    description: "Made it to the Dean's List",
    unlocked: false,
  },
  {
    id: "honor_roll",
    name: "Honor Roll",
    icon: "🏆",
    category: "Achievement",
    description: "Achieved Honor Roll status",
    unlocked: false,
  },
  {
    id: "graduate",
    name: "Graduate",
    icon: "🎓",
    category: "Achievement",
    description: "Successfully graduated",
    unlocked: false,
  },
  {
    id: "scholarship",
    name: "Scholar",
    icon: "💎",
    category: "Achievement",
    description: "Received scholarships",
    unlocked: false,
  },
  //Interest Stamps
  {
    id: "technology",
    name: "Tech Enthusiast",
    icon: "💻",
    category: "Interest",
    description: "Passionate about technology",
    unlocked: false,
  },
  {
    id: "sports",
    name: "Athletic Spirit",
    icon: "⚽",
    category: "Interest",
    description: "Active in sports",
    unlocked: false,
  },
  {
    id: "leadership",
    name: "Natural Leader",
    icon: "👑",
    category: "Interest",
    description: "Demonstrated leadership skills",
    unlocked: false,
  },
  {
    id: "community",
    name: "Community Helper",
    icon: "🤝",
    category: "Interest",
    description: "Engaged in community service",
    unlocked: false,
  },
  {
    id: "research",
    name: "Research Pioneer",
    icon: "🔍",
    category: "Interest",
    description: "Involved in research projects",
    unlocked: false,
  },
  {
    id: "international",
    name: "Global Citizen",
    icon: "🌍",
    category: "Interest",
    description: "International experience",
    unlocked: false,
  },
];
